name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14' 

      - name: Install dependencies
        working-directory: fullstack_open_part3_exercises
        run: npm install  

      - name: Check style
        working-directory: fullstack_open_part3_exercises
        run: npm run lint

      - name: Run build
        working-directory: phone-info/phone-app
        run: |
          npm install
          npm run build

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress:open
          start: npm run start:test
          working-directory: phone-info/phone-app && fullstack_open_part3_exercises
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          wait-on: http://localhost:3001
        
          
         