name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      # Backend setup and tests
      - name: "Backend: Install dependencies"
        working-directory: fullstack_open_part3_exercises
        run: npm install

      - name: "Backend: Start server for tests"
        working-directory: fullstack_open_part3_exercises
        run: npm run start:test

      # Frontend setup and tests with Cypress
      - name: "Frontend: Install dependencies"
        working-directory: phone-info/phone-app
        run: npm install

      - name: "Frontend: Run Cypress tests"
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress:open
          start: npm run start-prod
          wait-on: http://localhost:3001
          working-directory: phone-info/phone-app
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
