name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14' 

      - name: Install dependencies for backend
        working-directory: fullstack_open_part3_exercises
        run: npm install  

      - name: Check style for backend
        working-directory: fullstack_open_part3_exercises
        run: npm run lint

      - name: Run tests
        working-directory: fullstack_open_part3_exercises
        run: npm run dev
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}
          wait-on: http://localhost:3001

      - name: Run Cypress tests for frontend
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress:open
          start: npm run start
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}
          wait-on: http://localhost:3000
