name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' 

      - name: Install dependencies for backend
        working-directory: fullstack_open_part3_exercises
        run: npm install  

      - name: Check style for backend
        working-directory: fullstack_open_part3_exercises
        run: npm run lint

      - name: Run build for frontend
        working-directory: phone-info/phone-app
        run: |
          npm install
          npm run build

      - name: start backend
        working-directory: fullstack_open_part3_exercises
        run: npm run start:test &&
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}
         
      - name: Run Cypress tests for frontend
        uses: cypress-io/github-action@v5
       
        with:
          command: npm run cypress:open 
          working-directory: phone-info/phone-app
         
      - name: Stop servers
        run: |
          pkill -f 'node index.js' || true
          pkill -f 'react-scripts start' || true
